apiVersion: v1
kind: Namespace
metadata:
  name: mandatkollen
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
  name: mandatkollen
  namespace: mandatkollen
spec:
  ports:
  - port: 80
  selector:
    app: mandatkollen
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandatkollen
  namespace: mandatkollen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mandatkollen
  template:
    metadata:
      labels:
        app: mandatkollen
    spec:
      containers:
      - image: registry.iteam.services/iteam1337_mandatkollen:v0.43.0@sha256:08172e5a3915546681e6b852d83fed02c9c747d4d6a26603fd3bfccfe5fbd4a8
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        name: mandatkollen
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
    kubernetes.io/ingress.class: nginx
  name: mandatkollen-ingress
  namespace: mandatkollen
spec:
  rules:
  - host: mandatkollen.se
    http:
      paths:
      - backend:
          service:
            name: mandatkollen
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mandatkollen.se
    secretName: mandatkollen-prod-tls
