apiVersion: v1
kind: Namespace
metadata:
  name: mandatkollen
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
  name: mandatkollen
  namespace: mandatkollen
spec:
  ports:
  - port: 80
  selector:
    app: mandatkollen
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandatkollen
  namespace: mandatkollen
spec:
  selector:
    matchLabels:
      app: mandatkollen
  template:
    metadata:
      labels:
        app: mandatkollen
    spec:
      containers:
      - image: registry.iteam.services/iteam1337_mandatkollen:dd0e532-dirty@sha256:d008a3c20c4c487e11347de37f2adbf707c92385faa241fc5915443f7486ae61
        name: mandatkollen
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
    kubernetes.io/ingress.class: nginx
  name: mandatkollen-ingress
  namespace: mandatkollen
spec:
  rules:
  - host: mandatkollen.se
    http:
      paths:
      - backend:
          service:
            name: mandatkollen
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mandatkollen.se
    secretName: mandatkollen-prod-tls
