apiVersion: v1
kind: Namespace
metadata:
  name: mandatkollen
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
  name: mandatkollen
  namespace: mandatkollen
spec:
  ports:
  - port: 80
  selector:
    app: mandatkollen
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandatkollen
  namespace: mandatkollen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mandatkollen
  template:
    metadata:
      labels:
        app: mandatkollen
    spec:
      containers:
      - image: registry.iteam.services/iteam1337_mandatkollen:v0.50.0@sha256:7a4c2dbd177c4dabfc96a9a151d03a90afef8e27df103929d3f71c832714d0ec
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        name: mandatkollen
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self'";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 0";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Cross-Origin-Resource-Policy: same-site";
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
    nginx.ingress.kubernetes.io/proxy-pass-headers: Location
  name: mandatkollen-ingress
  namespace: mandatkollen
spec:
  rules:
  - host: mandatkollen.se
    http:
      paths:
      - backend:
          service:
            name: mandatkollen
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mandatkollen.se
    secretName: mandatkollen-prod-tls
