apiVersion: skaffold/v3
kind: Config
metadata:
  name: mandatkollen
build:
  artifacts:
    - image: iteam1337/mandatkollen
      platforms:
        - linux/amd64
  tagPolicy:
    sha256: {}
  local:
    tryImportMissing: true

manifests:
  rawYaml:
  - k8s/namespace.yaml
  - k8s/deployment.yaml
  - k8s/ingress.yaml
deploy:
  kubectl:
    flags:
      global:
        - --namespace=mandatkollen
