apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: mandatkollen
build:
  artifacts:
    - image: iteam1337/mandatkollen
deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/deployment.yaml
      - k8s/ingress.yaml
    flags:
      global:
        - --namespace=mandatkollen
