apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: mandatkollen-web
  name: mandatkollen-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flodeskollen-web
    spec:
      containers:
      - image: iteam1337/riksdagskollen
        name: flodeskollen-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
