apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: $KUBE_CLUSTER_CERTIFICATE
      server: $KUBE_CLUSTER_SERVER
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
current-context: default
kind: Config
preferences: {}
users:
  - name: default
    user:
      client-certificate-data: $KUBE_CERTIFICATE_DATA
      client-key-data: $KUBE_KEY_DATA
