apiVersion: v1
kind: Service
metadata:
  name: mandatkollen-eu
  namespace: mandatkollen
spec:
  ports:
    - port: 80
  type: ClusterIP
  selector:
    app: mandatkollen-eu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandatkollen-eu
  namespace: mandatkollen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mandatkollen-eu
  template:
    metadata:
      labels:
        app: mandatkollen-eu
    spec:
      containers:
        - name: mandatkollen-eu
          image: ghcr.io/iteam1337/mandatkollen:0.67.14 # {"$imagepolicy": "flux-system:mandatkollen"}
          command:
            - /bin/sh
            - -c
            - 'VITE_EU=true npm run build && npm run start'
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '200m'
              memory: '256Mi'
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
