apiVersion: v1
kind: Service
metadata:
  name: mandatkollen-service
spec:
  ports:
  - port: 80
  type: LoadBalancer
  selector:
    app: mandatkollen-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandatkollen-deployment
spec:
  selector:
    matchLabels:
      app: mandatkollen-deployment
  template:
    metadata:
      labels:
        app: mandatkollen-deployment
    spec:
      containers:
      - name: mandatkollen-deployment
        image: iteam1337/mandatkollen
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mandatkollen-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - mandatkollen.se
    secretName: mandatkollen-prod-tls
  rules:
  - host: mandatkollen.se
    http:
      paths:
      - backend:
          serviceName: mandatkollen-service
          servicePort: 3000