---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mandatkollen
  namespace: flux-system
spec:
  image: ghcr.io/iteam1337/mandatkollen
  interval: 30s
  provider: generic
