apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mandatkollen-ingress
  namespace: mandatkollen
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
    nginx.ingress.kubernetes.io/configuration-snippet: |   
      add_header X-Frame-Options "sameorigin";
      add_header X-Content-Type-Options nosniff;
      add_header Referrer-Policy 'same-origin';
      add_header Permissions-Policy "";
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
      add_header Content-Security-Policy: default-src 'self' matomo.iteam.services
      
spec:
  tls:
    - hosts:
        - mandatkollen.se
      secretName: mandatkollen-prod-tls
  rules:
    - host: mandatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mandatkollen
                port:
                  number: 80
