# This is a basic workflow to help you get started with Actions

name: Build & Deploy to Dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
          restore-keys: |
            fixed-${{ github.sha }}
            fixed-
      
      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          command: build
          cache-file: .skaffold/cache
          repository: registry.iteam.services

      - name: build-and-deploy
        run: |
          npm version patch
          npm run release

      - name: Push to git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release to Flux
          file_pattern: kustomize/latest.yaml
